CREATE TABLE IF NOT EXISTS atl_details (
    id INT AUTO_INCREMENT PRIMARY KEY,
    school_name VARCHAR(255) NOT NULL,
    sanction_no VARCHAR(255),
    udise VARCHAR(255),
    fund_date DATE,
    inauguration_date DATE,
    principal_name_phone VARCHAR(255),
    atl_code VARCHAR(255),
    atl_pswd VARCHAR(255),
    gem_code VARCHAR(255),
    govt_email VARCHAR(255),
    pfms VARCHAR(255),
    pfms_op VARCHAR(255),
    pfms_ap VARCHAR(255),
    atl_incharge_phone VARCHAR(255),
    dashbrd_pswd VARCHAR(255),
    gem_pswd VARCHAR(255),
    govt_mail_pswd VARCHAR(255),
    pfms_pswd VARCHAR(255),
    op_pswd VARCHAR(255),
    ap_pswd VARCHAR(255),
    reg_email VARCHAR(255),
    reg_phone VARCHAR(255),
    bharatkosh VARCHAR(255),
    bkosh_password VARCHAR(255),
    atl_vendor VARCHAR(255),
    vcomment TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
); 